//! Rust codegen — walks a `ViFile` AST and emits Rust source using the P02 Layer 2 API.
//!
//! Generated code targets a `no_std + alloc` environment (ViCell Cell context).
//! Output uses `alloc::format!`, `alloc::vec![]`, `alloc::boxed::Box` explicitly.
//!
//! # Usage
//!
//! ```ignore
//! let file = vi_compiler::compile_str(src)?;
//! let mut gen = CodeGen::new();
//! let rust_src = gen.generate(&file);
//! ```

use std::prelude::v1::*;
use crate::ast::{Binding, CallbackBinding, Component, Element, Expr, ViFile};
use crate::eval::{eval_binding, eval_callback, eval_property, AugOp, InterpolPart, TypedExpr};

// ─── Element → Widget mapping ────────────────────────────────────────────────

/// Maps a `.vi` element name to (Rust type, import path segment).
fn map_element(name: &str) -> Option<(&'static str, &'static str)> {
    match name {
        "VerticalLayout" | "VBox"  => Some(("Column", "column")),
        "HorizontalLayout" | "HBox" => Some(("Row",   "row")),
        "Text" | "Label"           => Some(("Label",  "label")),
        "Button"                   => Some(("Button", "button")),
        _ => None,
    }
}

/// Maps a `.vi` property type string to a Rust type string.
fn rust_type(ty: &str) -> &str {
    match ty {
        "int"    => "i32",
        "float"  => "f32",
        "string" => "alloc::string::String",
        "bool"   => "bool",
        "color"  => "viui::canvas::Color",
        "length" => "f32",
        _        => "i32", // fallback
    }
}

/// Default Rust expression for initialising a Signal<T> with a given type.
fn default_signal_init(ty: &str) -> &str {
    match ty {
        "int"    => "Signal::new(0i32)",
        "float"  => "Signal::new(0.0f32)",
        "string" => "Signal::new(alloc::string::String::new())",
        "bool"   => "Signal::new(false)",
        "color"  => "Signal::new(viui::canvas::Color::TRANSPARENT)",
        "length" => "Signal::new(0.0f32)",
        _        => "Signal::new(0i32)",
    }
}

// ─── CodeGen ─────────────────────────────────────────────────────────────────

/// State carried during emission of one component.
struct CompState {
    clone_counter: usize,
    sub_counter:   usize,
    widget_counter: usize,
    /// Imports needed: widget type names found during traversal.
    needs_column: bool,
    #[allow(dead_code)]
    needs_row:    bool,
    needs_label:  bool,
    needs_button: bool,
    needs_color:  bool,
}

impl CompState {
    fn new() -> Self {
        Self {
            clone_counter:  0,
            sub_counter:    0,
            widget_counter: 0,
            needs_column: false,
            needs_row:    false,
            needs_label:  false,
            needs_button: false,
            needs_color:  false,
        }
    }

    fn next_clone(&mut self, base: &str) -> String {
        let n = self.clone_counter;
        self.clone_counter += 1;
        format!("_{}_c{}", base, n)
    }

    fn next_sub(&mut self) -> String {
        let n = self.sub_counter;
        self.sub_counter += 1;
        format!("_sub_text_{}", n)
    }

    fn next_widget(&mut self, ty: &str) -> String {
        let n = self.widget_counter;
        self.widget_counter += 1;
        format!("w_{}_{}", ty.to_lowercase(), n)
    }
}

/// Code generator: produces Rust source from a `ViFile` AST.
pub struct CodeGen;

impl Default for CodeGen {
    fn default() -> Self { Self }
}

impl CodeGen {
    pub fn new() -> Self { Self }

    /// Generate Rust source for all components in `file`.
    pub fn generate(&mut self, file: &ViFile) -> String {
        let comp_sources: Vec<String> = file.components.iter().map(|c| self.gen_component(c)).collect();

        // Assemble preamble + component code.
        // NOTE: this file is designed to be include!()-ed into a no_std cell.
        //   - No #![...] inner attributes (would conflict with the enclosing crate)
        //   - No `extern crate alloc;` (the including file provides it)
        //   - #[allow(unused_imports)] guards unconditionally-emitted imports
        let mut out = String::new();
        out.push_str("// Generated by vi-compiler \u{2014} DO NOT EDIT\n");
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("use viui::signal::{Signal, SubscriptionHandle};\n");
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("use viui::node::ViNode;\n");
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("use viui::node_widgets::label::Label;\n");
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("use viui::node_widgets::button::Button;\n");
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("use viui::node_widgets::column::Column;\n");
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("use viui::node_widgets::row::Row;\n");
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("use viui::canvas::Color;\n");
        out.push('\n');

        for src in comp_sources { out.push_str(&src); }
        out
    }

    fn gen_component(&mut self, comp: &Component) -> String {
        let mut st = CompState::new();

        // ── Collect element tree info (imports, sub handles) ─────────────────
        let mut sub_fields: Vec<String>  = Vec::new(); // SubscriptionHandle field names
        let mut build_stmts: Vec<String> = Vec::new(); // lines inside build()

        // 1. Emit Signal declarations for in/out/in-out properties
        for prop in &comp.properties {
            let init = if let Some(Expr::Raw(r)) = &prop.default {
                typed_expr_to_rust(&eval_property(&r.text, &prop.ty), &prop.ty)
            } else {
                default_signal_init(&prop.ty).to_string()
            };
            build_stmts.push(format!("        let {} = {};", prop.name, init));
        }
        if !comp.properties.is_empty() { build_stmts.push(String::new()); }

        // 2. Walk element tree → collect widget stmts + subscription handles
        let root_widget = if let Some(root_elem) = comp.children.first() {
            let (stmts, subs, var_name) = self.gen_element(root_elem, &comp.properties.iter()
                .map(|p| p.name.as_str()).collect::<Vec<_>>(), &mut st);
            for s in stmts { build_stmts.push(s); }
            for sub in &subs { sub_fields.push(sub.clone()); }
            var_name
        } else {
            // No children → emit a placeholder Column
            "Column::new(alloc::vec![])".to_string()
        };

        // 3. Determine root widget type for return signature
        let root_ty = if let Some(root_elem) = comp.children.first() {
            map_element(&root_elem.name).map(|(t, _)| t).unwrap_or("Column")
        } else {
            "Column"
        };

        // ── Emit struct ───────────────────────────────────────────────────────
        let mut out = String::new();
        out.push_str(&format!("/// Generated component: {}\n", comp.name));
        out.push_str(&format!("pub struct {} {{\n", comp.name));
        for prop in &comp.properties {
            let rty = rust_type(&prop.ty);
            // Only emit public fields for in/out/in-out visibility
            let vis = prop.visibility.as_ref().map(|v| format!("{:?}", v)).unwrap_or_default();
            if vis != "Private" {
                out.push_str(&format!("    pub {}: Signal<{}>,\n", prop.name, rty));
            }
        }
        for sub_name in &sub_fields {
            out.push_str(&format!("    {}: SubscriptionHandle,\n", sub_name));
        }
        out.push_str("}\n\n");

        // ── Emit impl ─────────────────────────────────────────────────────────
        out.push_str(&format!("impl {} {{\n", comp.name));
        out.push_str(&format!("    pub fn build() -> (Self, {}) {{\n", root_ty));
        for s in &build_stmts { out.push_str(s); out.push('\n'); }

        // Return tuple
        let struct_fields: Vec<String> = comp.properties.iter()
            .map(|p| p.name.clone())
            .chain(sub_fields.iter().cloned())
            .collect();
        let fields_str = struct_fields.join(", ");
        out.push_str(&format!("        let state = Self {{ {} }};\n", fields_str));
        out.push_str(&format!("        (state, {})\n", root_widget));
        out.push_str("    }\n");
        out.push_str("}\n");
        out
    }

    /// Recursively generate code for one element.
    ///
    /// Returns: (statements to emit, subscription handle names, widget variable name/expr).
    fn gen_element(
        &mut self,
        elem: &Element,
        prop_names: &[&str],
        st: &mut CompState,
    ) -> (Vec<String>, Vec<String>, String) {
        let mut stmts: Vec<String> = Vec::new();
        let mut subs:  Vec<String> = Vec::new();

        match elem.name.as_str() {
            "VerticalLayout" | "VBox" | "HorizontalLayout" | "HBox" => {
                st.needs_column = true;
                let is_vertical = matches!(elem.name.as_str(), "VerticalLayout" | "VBox");
                let container_ty = if is_vertical { "Column" } else { "Row" };

                // Recurse children
                let mut child_vars: Vec<String> = Vec::new();
                for child in &elem.children {
                    let (child_stmts, child_subs, child_var) = self.gen_element(child, prop_names, st);
                    stmts.extend(child_stmts);
                    subs.extend(child_subs);
                    child_vars.push(child_var);
                }

                // Build child vec
                let vec_items: Vec<String> = child_vars.iter()
                    .map(|v| format!("alloc::boxed::Box::new({}) as alloc::boxed::Box<dyn ViNode>", v))
                    .collect();
                let vec_expr = format!("alloc::vec![{}]", vec_items.join(", "));

                let var = st.next_widget(container_ty);

                // Extract layout properties
                let padding = find_binding_f32(&elem.bindings, "padding");
                let spacing = find_binding_f32(&elem.bindings, "spacing");

                let mut init = format!("{}::new({})", container_ty, vec_expr);
                if let Some(p) = padding { init = format!("{}.with_padding({}f32)", init, p); }
                if let Some(s) = spacing { init = format!("{}.with_spacing({}f32)", init, s); }

                stmts.push(format!("        let {} = {};", var, init));
                stmts.push(String::new());
                (stmts, subs, var)
            }

            "Text" | "Label" => {
                st.needs_label = true;
                let var = st.next_widget("Label");

                // text binding
                let text_expr = if let Some(b) = elem.bindings.iter().find(|b| b.property == "text") {
                    match &b.value {
                        Expr::Raw(r) => eval_binding(&r.text, "text", "Text"),
                    }
                } else {
                    TypedExpr::StringLit(String::new())
                };

                let text_sig_var = match &text_expr {
                    TypedExpr::Interpolated(parts) => {
                        // Derive a Signal<String> from the source signal via map().into_parts()
                        let var_names: Vec<&str> = parts.iter()
                            .filter_map(|p| if let InterpolPart::Var(v) = p { Some(v.as_str()) } else { None })
                            .collect();
                        // For simplicity: take the first variable name as the source signal
                        let src_sig = var_names.first().copied().unwrap_or("count");
                        let fmt_str = build_format_string(parts);
                        let format_args = build_format_args(parts);
                        let sub_name = st.next_sub();
                        let text_sig = format!("text_sig_{}", st.sub_counter - 1);
                        stmts.push(format!(
                            "        let ({}, {}) = {}.map(|n| alloc::format!(\"{}\", {})).into_parts();",
                            text_sig, sub_name, src_sig, fmt_str, format_args
                        ));
                        stmts.push(String::new());
                        subs.push(sub_name);
                        text_sig
                    }
                    TypedExpr::StringLit(s) => {
                        let sig_var = format!("text_sig_{}", st.sub_counter);
                        stmts.push(format!(
                            "        let {} = Signal::new(\"{}\".to_string());",
                            sig_var, escape_str(s)
                        ));
                        sig_var
                    }
                    other => {
                        let sig_var = format!("text_sig_{}", st.sub_counter);
                        stmts.push(format!(
                            "        let {} = Signal::new(alloc::format!(\"{{}}\", {}));",
                            sig_var, typed_expr_raw(other)
                        ));
                        sig_var
                    }
                };

                // color binding
                let color_expr = elem.bindings.iter().find(|b| b.property == "color")
                    .map(|b| match &b.value {
                        Expr::Raw(r) => color_typed_to_rust(&eval_binding(&r.text, "color", "Text")),
                    });

                let mut init = format!("Label::new({})", text_sig_var);
                if let Some(ce) = color_expr {
                    st.needs_color = true;
                    init = format!("{}.with_color({})", init, ce);
                }

                stmts.push(format!("        let {} = {};", var, init));
                stmts.push(String::new());
                (stmts, subs, var)
            }

            "Button" => {
                st.needs_button = true;
                let var = st.next_widget("Button");

                // text binding — buttons use &str label, not Signal
                let label_str = elem.bindings.iter()
                    .find(|b| b.property == "text")
                    .map(|b| match &b.value {
                        Expr::Raw(r) => {
                            match eval_binding(&r.text, "text", "Button") {
                                TypedExpr::StringLit(s) => s,
                                other => typed_expr_raw(&other),
                            }
                        }
                    })
                    .unwrap_or_default();

                // clicked callback
                let callback_body = gen_callback_body(&elem.callbacks, prop_names, st, &mut stmts);

                let init = format!("Button::new(\"{}\", {})", escape_str(&label_str), callback_body);
                stmts.push(format!("        let {} = {};", var, init));
                stmts.push(String::new());
                (stmts, subs, var)
            }

            unknown => {
                let var = format!("_unsupported_{}", unknown.to_lowercase());
                stmts.push(format!("        // TODO: unsupported element '{}' — emitted as empty Column", unknown));
                stmts.push(format!("        let {} = Column::new(alloc::vec![]);", var));
                stmts.push(String::new());
                st.needs_column = true;
                (stmts, subs, var)
            }
        }
    }
}

// ─── Emit helpers ─────────────────────────────────────────────────────────────

/// Emit Rust code for a callback binding.
/// Returns the closure expression to pass as the callback argument.
fn gen_callback_body(
    callbacks: &[CallbackBinding],
    _prop_names: &[&str],
    st: &mut CompState,
    stmts: &mut Vec<String>,
) -> String {
    let clicked = callbacks.iter().find(|c| c.name == "clicked");
    let Some(cb) = clicked else {
        return "|| {}".to_string();
    };

    let typed = eval_callback(&cb.body);
    match typed {
        TypedExpr::AugAssign { name, op, rhs } => {
            let clone_var = st.next_clone(&name);
            stmts.push(format!("        let {} = {}.clone();", clone_var, name));
            let op_str = aug_op_to_method_body(&op, &rhs);
            format!("move || {{ {}.update(|n| {}); }}", clone_var, op_str)
        }
        _ => {
            // Fallback: emit raw body text
            format!("|| {{ {} }}", cb.body.trim())
        }
    }
}

fn aug_op_to_method_body(op: &AugOp, rhs: &TypedExpr) -> String {
    let rhs_str = typed_expr_raw(rhs);
    match op {
        AugOp::Add => format!("*n += {}", rhs_str),
        AugOp::Sub => format!("*n -= {}", rhs_str),
        AugOp::Mul => format!("*n *= {}", rhs_str),
        AugOp::Div => format!("*n /= {}", rhs_str),
    }
}

fn typed_expr_to_rust(expr: &TypedExpr, ty: &str) -> String {
    match expr {
        TypedExpr::IntLit(n) => {
            let suffix = match ty { "float" | "length" => "f32", _ => "i32" };
            format!("Signal::new({}{suffix})", n)
        }
        TypedExpr::StringLit(s) => format!("Signal::new(\"{}\".to_string())", escape_str(s)),
        TypedExpr::Ident(s)     => format!("Signal::new({}.into())", s),
        _ => default_signal_init(ty).to_string(),
    }
}

fn typed_expr_raw(expr: &TypedExpr) -> String {
    match expr {
        TypedExpr::IntLit(n)     => n.to_string(),
        TypedExpr::StringLit(s)  => format!("\"{}\"", escape_str(s)),
        TypedExpr::LengthLit(f)  => format!("{}f32", f),
        TypedExpr::Ident(s)      => s.clone(),
        TypedExpr::ColorLit { r, g, b } => format!("Color::rgb({}, {}, {})", r, g, b),
        _ => "()".to_string(),
    }
}

fn color_typed_to_rust(expr: &TypedExpr) -> String {
    match expr {
        TypedExpr::ColorLit { r, g, b } => format!("Color::rgb({}, {}, {})", r, g, b),
        TypedExpr::Ident(s) => s.clone(),
        _ => "Color::WHITE".to_string(),
    }
}

/// Build the format string part of `alloc::format!("...", ...)`
/// by replacing `\{var}` placeholders with `{}`.
fn build_format_string(parts: &[InterpolPart]) -> String {
    parts.iter().map(|p| match p {
        InterpolPart::Literal(s) => s.replace('{', "{{").replace('}', "}}"),
        InterpolPart::Var(_)     => "{}".to_string(),
    }).collect()
}

/// Build the argument list after the format string, one arg per `Var` part.
fn build_format_args(parts: &[InterpolPart]) -> String {
    let vars: Vec<&str> = parts.iter()
        .filter_map(|p| if let InterpolPart::Var(v) = p { Some(v.as_str()) } else { None })
        .collect();
    // In the closure body `n` is the dereferenced source value
    // (closure signature is `|n| alloc::format!(...)`)
    vars.iter().map(|_| "n").collect::<Vec<_>>().join(", ")
}

fn find_binding_f32(bindings: &[Binding], prop: &str) -> Option<f32> {
    bindings.iter().find(|b| b.property == prop).and_then(|b| {
        let Expr::Raw(r) = &b.value;
        match eval_binding(&r.text, prop, "") {
            TypedExpr::LengthLit(f) => Some(f),
            TypedExpr::IntLit(n)    => Some(n as f32),
            _ => None,
        }
    })
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
