#!/usr/bin/env python3
"""Hypha mock LLM proxy — host-side plumbing test for the llm-gateway cell.

Purpose (os-gap G3 de-risk): isolate the *Cellos side* of the LLM path
(cell -> net -> TLS -> HTTP -> JSON parse) from the real provider. This is NOT
a real LLM. It speaks TLS 1.3 with a self-signed P-256 cert (Cellos's net cell
uses embedded-tls `UnsecureProvider`, so it does not verify the cert) and
answers any `POST /v1/chat/completions` with an OpenAI-compatible JSON that
echoes the prompt back — proving the round-trip end to end.

P2 tool simulation: if the prompt contains keywords like "list", "files", etc.
the mock returns a TOOL_CALL: reply. If the prompt already contains
"TOOL_RESULT:" the mock synthesises a final text answer from it.

P3 tool simulation: "list cells", "running", "processes" → list_cells
"sys info", "os version" → sys_info
"lookup service", "which tid" → lookup_service
"spawn", "launch" → spawn_cell
"kill", "stop cell" → kill_cell

Run on the HOST (the guest reaches it at 10.0.2.2:8443 via QEMU user-net):
    python tools/hypha-mock-llm/mock_proxy.py           # TLS mode
    python tools/hypha-mock-llm/mock_proxy.py --plain   # HTTP (plaintext)
Then in the Cellos shell:
    hypha

Requires QEMU user-mode (SLIRP) networking, where guest 10.0.2.2 == host.
"""

import json
import os
import re
import ssl
import sys
from http.server import BaseHTTPRequestHandler, HTTPServer

HOST = "0.0.0.0"
PORT = 8443
HERE = os.path.dirname(os.path.abspath(__file__))
CERT = os.path.join(HERE, "cert.pem")
KEY = os.path.join(HERE, "key.pem")


def ensure_cert():
    """Verify that cert.pem / key.pem exist and are CA-signed.

    cert.pem and key.pem are generated by gen-dev-ca.py — a CA-signed P-256
    server cert (SAN DNS=mock, IP=10.0.2.2) whose CA is embedded in the
    Cellos net service as `cells/services/net/roots/private.der`.  The old
    self-signed cert no longer works because the net service now verifies the
    server certificate against that embedded CA.

    Run gen-dev-ca.py once to (re)generate everything, then rebuild:
        python tools/hypha-mock-llm/gen-dev-ca.py
        cargo build --release -p service-net
        ./gen_disk.ps1
    """
    if os.path.exists(CERT) and os.path.exists(KEY):
        return
    sys.exit(
        f"Missing {CERT} or {KEY}.\n"
        "Run `python tools/hypha-mock-llm/gen-dev-ca.py` to generate them.\n"
        "Then rebuild service-net and regenerate the disk:\n"
        "  cargo build --release -p service-net\n"
        "  ./gen_disk.ps1"
    )


# ── P2 + P3 tool simulation ──────────────────────────────────────────────────

def _user_message(prompt: str) -> str:
    """Extract the last `user: ...` line from a role-tagged Cellos prompt.
    Falls back to the whole prompt so the mock still works for P1 plain echo."""
    for line in reversed(prompt.splitlines()):
        if line.startswith("user: "):
            return line[6:]
    return prompt


def _has_tool_result_line(prompt: str) -> bool:
    """True only when the prompt contains an actual `tool_result:` protocol line
    (starts at column 0). Ignores the SYSTEM_PREAMBLE text that mentions
    TOOL_RESULT: in prose."""
    for line in prompt.splitlines():
        if line.startswith("tool_result:"):
            return True
    return False


def _tool_call_for(prompt: str) -> str | None:
    """Return a TOOL_CALL: string when the USER'S MESSAGE implies a tool.
    Checks only the last `user:` line — ignores the system preamble keywords.
    Returns None on post-tool turns so the caller synthesizes text instead."""
    if _has_tool_result_line(prompt):
        return None  # post-tool turn: synthesize text (handled by caller)

    user = _user_message(prompt).lower()

    # P3 — sys tools (check before generic "list" so "list cells" routes here)
    if any(w in user for w in ("list cells", "running cells", "list processes",
                                "what cells", "what processes")):
        return 'TOOL_CALL: {"name":"list_cells","args":{}}'

    if any(w in user for w in ("sys info", "system info", "os version",
                                "os info", "version info", "what os")):
        return 'TOOL_CALL: {"name":"sys_info","args":{}}'

    if re.search(r'lookup service|which tid|service tid|find service', user):
        m = re.search(r'\b(vfs|net|input|config|compositor)\b', user)
        svc = m.group(1) if m else "vfs"
        return f'TOOL_CALL: {{"name":"lookup_service","args":{{"name":"{svc}"}}}}'

    # P3 — spawn tools
    if re.search(r'\bspawn\b|\blaunch cell\b|\bstart cell\b', user):
        m = re.search(r'/\S+', _user_message(prompt))
        path = m.group(0) if m else "/bin/nc"
        return f'TOOL_CALL: {{"name":"spawn_cell","args":{{"path":"{path}"}}}}'

    if re.search(r'\bkill\b|\bstop cell\b|\bterminate cell\b', user):
        m = re.search(r'\btid[=:\s]+(\d+)', user)
        tid = int(m.group(1)) if m else 5
        return f'TOOL_CALL: {{"name":"kill_cell","args":{{"tid":{tid}}}}}'

    # P2 — fs tools
    if any(w in user for w in ("list", "files", "ls ", "what's in", "what is in",
                                "dir ", "folder", "directory")):
        m = re.search(r'(/\w+)', _user_message(prompt))
        path = m.group(1) if m else "/data"
        return f'TOOL_CALL: {{"name":"list_dir","args":{{"path":"{path}"}}}}'

    if re.search(r'read|contents? of|show me', user):
        m = re.search(r'(/\S+)', _user_message(prompt))
        path = m.group(1) if m else "/data/notes.txt"
        return f'TOOL_CALL: {{"name":"read_file","args":{{"path":"{path}"}}}}'

    return None


def _text_reply(prompt: str) -> str:
    """Synthesise a plain text reply — either post-tool or a plain echo."""
    if _has_tool_result_line(prompt):
        # Collect the last tool_call + tool_result pair for context.
        tool_name = ""
        snippet = "(no result)"
        for line in prompt.splitlines():
            if line.startswith("tool_call:"):
                tool_name = line[len("tool_call:"):].split()[0].strip() if line[len("tool_call:"):].split() else ""
            if line.startswith("tool_result:"):
                snippet = line[len("tool_result:"):].strip()[:200]
        prefixes = {
            "list_dir":        "Here are the files I found: ",
            "read_file":       "Here is the file content: ",
            "write_file":      "File written successfully. ",
            "list_cells":      "Here are the running cells: ",
            "sys_info":        "System information: ",
            "lookup_service":  "Service lookup result: ",
            "spawn_cell":      "Cell spawned: ",
            "kill_cell":       "Cell terminated: ",
        }
        prefix = prefixes.get(tool_name, "Tool result: ")
        return prefix + snippet + ". Is there anything else?"

    return (
        "Mock LLM here - the Cellos TLS+HTTP+JSON path works. "
        "You sent: " + _user_message(prompt)[-160:].replace("\n", " ")
    )


# ── HTTP handler ─────────────────────────────────────────────────────────────

class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        print("[mock-llm] " + (fmt % args))

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length) if length else b""
        prompt = ""
        try:
            msgs = json.loads(raw or b"{}").get("messages", [])
            if msgs:
                prompt = msgs[-1].get("content", "")
        except Exception:
            pass

        tool_call = _tool_call_for(prompt)
        if tool_call:
            reply = tool_call
            print(f"[mock-llm] -> tool call: {tool_call[:80]}")
        else:
            reply = _text_reply(prompt)
            print(f"[mock-llm] -> text reply")

        body = json.dumps({
            "id": "mock-1",
            "object": "chat.completion",
            "choices": [{"index": 0, "message": {"role": "assistant", "content": reply}}],
        }).encode()

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def main():
    # A logging print must NEVER crash a request handler. On a Windows cp1252
    # console an unencodable char (e.g. a Unicode arrow) raises UnicodeEncodeError
    # mid-do_POST, killing the response so the TLS client hangs waiting for a
    # reply that never comes. Force UTF-8 with a non-fatal error handler.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="backslashreplace")
        except (AttributeError, ValueError):
            pass

    plain = "--plain" in sys.argv
    port = 8080 if plain else PORT

    httpd = HTTPServer((HOST, port), Handler)
    if plain:
        print(f"[mock-llm] PLAIN HTTP mock LLM listening on {HOST}:{port}")
        print(f"[mock-llm] guest reaches it at 10.0.2.2:{port} (QEMU user-net)")
        print(f"[mock-llm] P3 tool simulation active — files/dirs, cells, spawn/kill")
    else:
        ensure_cert()
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.minimum_version = ssl.TLSVersion.TLSv1_3  # embedded-tls is TLS 1.3 only
        ctx.load_cert_chain(CERT, KEY)
        httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
        print(f"[mock-llm] TLS 1.3 mock LLM listening on {HOST}:{port}")
        print(f"[mock-llm] guest reaches it at 10.0.2.2:{port} (QEMU user-net)")

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n[mock-llm] bye")


if __name__ == "__main__":
    main()
